
spring:
  application:
    name: zuul-api-gateway

server:
  port: 8762
      
zuul:
  ignored-services: '*'
  routes:
   user-registration-service: 
     path: /api/**
     service-id: user-registration-service

user-registration-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 60000
    ReadTimeout: 60000
    ConnectTimeout: 60000
     
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 600000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true      
 
