
spring:
  application:
    name: zuul-server

zuul:
  ignored-services: "*"
  routes:
   user-registration-service: 
     path: /api/**
     service-id: user-registation-service
  host:
    socket-timeout-millis: 60000

server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://discovery-server:8761/eureka/
    availability-zones:
      region1: zone1
      
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
       timeout:
          enabled: false
       isolation:
         thread:
           timeoutInMilliseconds: 12000
