
spring:
  application:
    name: zuul-server

zuul:
  ignored-services: "*"
  routes:
   user-registration-service: 
     path: /registration/**
     service-id: user-registration-service

server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://discovery-server:8761/eureka/
    availability-zones:
      region1: zone1
